### ISSUE TITLE
Add GET endpoint for getting all of a user's conversations

### ISSUE THREAD

**Issue by igorveselinovic** [schramm-famm/ether#10]
`GET /ether/v1/conversations`

The handler should use the `User-ID` header to identify the user.

The returned list of conversations probably only needs to support sorting by most recent to least recent.

Response Body:
```
{
    "conversations": [
        {
            "id": 1,
            "name": "foo",
            "description": "bar"
        },
        ...
    ]
}
```

**Comment by Thao-Tran** [comment]
To support the sorting from most recent to least recent, #23 should probably be completed first.
